/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.io.IOException;

public class MainTest {
	@Test public void testMain() throws IOException {
		//
	}
}
