/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//import org.junit.AfterClass;
//import org.junit.BeforeClass;
//import org.junit.Test;
//
//import main.Main;
//
//import static org.junit.Assert.assertEquals;
//import static org.junit.Assert.assertFalse;
//import static org.junit.Assert.assertTrue;
//import static org.junit.Assert.fail;

public class MainTest {
//	private static Main d = null;
//
//	@BeforeClass
//	public static void initAll() {
//		System.out.println("Create d");
//		d = new Main();
//	}
//
//	@AfterClass
//	public static void tearDownAll() {
//		System.out.println("Deallocate d");
//		d = null;
//	}
//
//	@Test
//	public void testAddition() {
//		assertEquals(3, d.addition(1, 2));
//		assertEquals(-2, d.addition(-5, 3));
//	}
//
//	@Test
//	public void testDivision() {
//		float res = d.divide(16, 4);
//		assertTrue(4 == res);
//		assertFalse(4 == d.divide(9, 3));
//		//assertThrows(ArithmeticException.class, () -> {
//		//	d.divide(7, 0);
//		//});
//	}
}
